const {test,expect}=require('@playwright/test');
async function login(page){await page.goto('/login');await page.request.post('/api/auth/test-auto-login');
 // /login khi đã có phiên tự chuyển sang /app; goto ngay sau đó bị chính nó
 // cắt ngang. Đợi chuyển hướng tự động xong rồi mới đi tiếp.
 await page.waitForURL(/\/app/,{timeout:20000}).catch(()=>{});
 await page.goto('/app');await expect(page.locator('#appLayout')).toBeVisible()}
function fixtures(){
 const production_orders=[
  {id:1,po_id:1,code:'QA-PO-REPAIR-25',po_code:'QA-PO-REPAIR-25',product:'KHUNG MÁY',status:'IN_PROGRESS',planned_quantity:1000,good_quantity:620,progress_actual_good_qty:70,progress_planned_qty:150,progress_missing_operation_count:0,defect_quantity:38,repairable_quantity:21,repair_pending_quantity:25,estimated_repair_work_seconds:12600,repair_operation_count:2,repair_unconfigured_operation_count:0,scrap_quantity:17,remaining_quantity:380,progress_percent:46.7,terminal_operation_count:1,due_date:'2026-08-12'},
  {id:2,po_id:2,code:'QA-PO-REPAIR-3',po_code:'QA-PO-REPAIR-3',product:'THÙNG CARTON',status:'IN_PROGRESS',planned_quantity:500,good_quantity:120,progress_actual_good_qty:100,progress_planned_qty:200,progress_missing_operation_count:0,defect_quantity:10,repairable_quantity:3,repair_pending_quantity:3,estimated_repair_work_seconds:0,repair_operation_count:1,repair_unconfigured_operation_count:1,scrap_quantity:7,remaining_quantity:380,progress_percent:50,terminal_operation_count:1,due_date:'2026-08-08'},
  {id:3,po_id:3,code:'QA-PO-REPAIR-0',po_code:'QA-PO-REPAIR-0',product:'KHUNG NHỎ',status:'IN_PROGRESS',planned_quantity:0,good_quantity:0,progress_actual_good_qty:0,progress_planned_qty:0,progress_missing_operation_count:1,defect_quantity:2,repairable_quantity:0,repair_pending_quantity:0,estimated_repair_work_seconds:0,repair_operation_count:0,repair_unconfigured_operation_count:0,scrap_quantity:2,remaining_quantity:0,progress_percent:null,terminal_operation_count:1,due_date:'2026-08-15'}];
 const operations=[];[['WELD','Hàn',12],['PACK','Đóng gói',13]].forEach((x,i)=>operations.push({po_id:1,po_code:'QA-PO-REPAIR-25',part_id:1,part_code:'FRAME',part_name:'Khung máy',operation_id:10+i,operation_sort:i,operation_code:x[0],operation_name:x[1],done_qty:620,defect_qty:20,rework_qty:x[2],repair_pending_quantity:x[2],repair_cycle_time_seconds_per_unit:504,estimated_repair_work_seconds:x[2]*504,progress_percent:62,control_state:'ON_TRACK',due_date:'2026-08-12'}));operations.push({po_id:2,po_code:'QA-PO-REPAIR-3',part_id:2,part_code:'BOX',part_name:'Thùng',operation_id:20,operation_sort:1,operation_code:'GLUE',operation_name:'Dán keo',done_qty:120,defect_qty:10,rework_qty:3,repair_pending_quantity:3,repair_cycle_time_seconds_per_unit:0,estimated_repair_work_seconds:0,progress_percent:24,control_state:'CRITICAL',due_date:'2026-08-08'});operations.push({po_id:3,po_code:'QA-PO-REPAIR-0',part_id:3,part_code:'SMALL',part_name:'Khung nhỏ',operation_id:30,operation_sort:1,operation_code:'QC',operation_name:'Kiểm tra',done_qty:50,defect_qty:2,rework_qty:0,repair_pending_quantity:0,repair_cycle_time_seconds_per_unit:0,estimated_repair_work_seconds:0,progress_percent:50,control_state:'ON_TRACK',due_date:'2026-08-15'});return {production_orders,operations}}
async function mock(page){const data=fixtures();await page.route('**/api/dashboard/overview*',r=>r.fulfill({json:{ok:true,...data,summary:{}}}));await page.route('**/api/production-control*',r=>r.fulfill({json:{ok:true,production_orders:data.production_orders.map(x=>({po_id:x.po_id,control_state:x.po_id===2?'CRITICAL':'ON_TRACK'})),operations:data.operations,summary:{}}}))}
async function open(page){await page.evaluate(()=>openPage('overview'));await expect(page.locator('.overview-po')).toHaveCount(3)}
for(const viewport of [{width:1920,height:1080},{width:1366,height:768},{width:390,height:844}])test(`repair backlog ${viewport.width}x${viewport.height}`,async({page})=>{await page.setViewportSize(viewport);await mock(page);await login(page);await open(page);await expect(page.locator('[data-compact-po="1"] .compact-repair')).toHaveText('25 SP');await expect(page.locator('[data-po-section="1"]')).toContainText('CẦN SỬA25 SP');await expect(page.locator('[data-po-section="2"]')).toContainText('CHƯA CÓ ĐỊNH MỨC SỬA');await expect(page.locator('[data-po-section="3"]')).toContainText('Không có hàng chờ sửa');expect(await page.locator('body').evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(false);await page.screenshot({path:`test-results/repair-backlog-${viewport.width}x${viewport.height}.png`,fullPage:true})});
test('repair filter and largest backlog sort',async({page})=>{await page.setViewportSize({width:1920,height:1080});await mock(page);await login(page);await open(page);await page.locator('#ovRepair').selectOption('pending');await page.locator('#ovSort').selectOption('repair_qty');await expect(page.locator('.overview-po')).toHaveCount(2);await expect(page.locator('.overview-po').first()).toContainText('25 SP');await expect(page.locator('.overview-po').first()).toContainText('3,5 GIỜ CÔNG');await expect(page.locator('#ovRepairPlan')).toContainText('1,8 GIỜ CÔNG')});
test('multi-PO progress is per-card and top total uses weighted operation output',async({page})=>{await page.setViewportSize({width:1366,height:768});await mock(page);await login(page);await open(page);await expect(page.locator('#ovKpis')).toContainText('Tiến độ theo công đoạn');await expect(page.locator('[data-po-section="1"]')).not.toContainText('950 đạt');await expect(page.locator('[data-po-section="1"]')).not.toContainText('Đạt 5.643 / 46.550');await expect(page.locator('#ovKpis')).not.toContainText('Thành phẩm hoàn tất');await expect(page.locator('#ovKpis')).not.toContainText('Còn lại');await expect(page.locator('[data-po-section="1"]')).toContainText('Tiến độ sản lượng theo công đoạn: 46,7%');await expect(page.locator('[data-po-section="2"]')).toContainText('Tiến độ sản lượng theo công đoạn: 50%');await expect(page.locator('[data-po-section="3"]')).toContainText('Chưa có định mức sản lượng');await page.locator('#ovPoFilter').selectOption('1');await expect(page.locator('#ovKpis')).toContainText('46,7%');expect(await page.locator('body').evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(false)});
for(const width of [390,414])test(`multi-PO cards remain readable at ${width}px`,async({page})=>{await page.setViewportSize({width,height:844});await mock(page);await login(page);await open(page);await expect(page.locator('.overview-po')).toHaveCount(3);await expect(page.locator('[data-po-section="1"]')).not.toContainText('950 đạt');await expect(page.locator('[data-po-section="1"]')).not.toContainText('Đạt 5.643 / 46.550');await expect(page.locator('#ovKpis')).not.toContainText('Thành phẩm hoàn tất');await expect(page.locator('#ovKpis')).not.toContainText('Còn lại');await expect(page.locator('[data-po-section="1"]')).toContainText('Tiến độ sản lượng theo công đoạn: 46,7%');await expect(page.locator('[data-po-section="2"]')).toContainText('Tiến độ sản lượng theo công đoạn: 50%');expect(await page.locator('body').evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(false)});
for(const viewport of [{width:1366,height:768},{width:1920,height:1080}])test(`compact PO summary shares all six desktop columns at ${viewport.width}px`,async({page})=>{await page.setViewportSize(viewport);await mock(page);await login(page);await open(page);const head=page.locator('.overview-compact-head');const rows=page.locator('.overview-compact-po');await expect(head).toHaveCount(1);await expect(head.locator(':scope > *')).toHaveCount(6);await expect(rows).toHaveCount(3);await expect(rows.locator(':scope > *')).toHaveCount(6*3);await expect(head).toHaveClass(/overview-compact-grid/);await expect(rows.first()).toHaveClass(/overview-compact-grid/);const columns=await page.locator('.overview-compact-head, .overview-compact-po').evaluateAll(items=>items.map(item=>({template:getComputedStyle(item).gridTemplateColumns,cells:[...item.children].map(cell=>{const box=cell.getBoundingClientRect();return {x:Math.round(box.x),right:Math.round(box.right)}})})));expect(columns.every(item=>item.template===columns[0].template&&item.cells.length===6&&item.cells.every((cell,index)=>Math.abs(cell.x-columns[0].cells[index].x)<=1&&(index===5||cell.right<=item.cells[index+1].x)))).toBe(true);const textAlignment=await page.locator('.overview-compact-head, .overview-compact-po').evaluateAll(items=>{const head=items[0];return items.slice(1).every(row=>[1,4].every(index=>getComputedStyle(head.children[index]).textAlign===getComputedStyle(row.children[index]).textAlign&&getComputedStyle(row.children[index]).textAlign!=='right'))});expect(textAlignment).toBe(true);await expect(page.locator('[data-compact-po="1"] .compact-warning')).toBeEmpty();await expect(page.locator('[data-compact-po="3"] .compact-warning')).toContainText('1 công đoạn chưa có định mức');expect(await page.locator('body').evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(false)});
test('compact PO summary has no mobile overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await mock(page);await login(page);await open(page);await expect(page.locator('.overview-compact-po')).toHaveCount(3);expect(await page.locator('body').evaluate(x=>x.scrollWidth>x.clientWidth)).toBe(false);await expect(page.locator('[data-compact-po="3"] .compact-warning')).toContainText('1 công đoạn chưa có định mức')});
