const{test,expect}=require('@playwright/test');
async function login(page){await page.goto('/login');await page.request.post('/api/auth/test-auto-login');await page.goto('/app')}
const events=[
 {id:'9',event_type:'VALUE_CHANGED',category:'CHANGE',occurred_at:'2026-08-13T08:40:00Z',actor_id:1,actor_name:'Supervisor A',po_id:1,part_id:2,operation_id:3,session_id:77,title:'Điều chỉnh sản lượng Session',description:'Double scan correction',quantity_delta:null,metadata:{before:{good_qty:120},after:{good_qty:118}},correlation_id:'corr-fix',session_trace_id:'',source:'AUDIT'},
 {id:'8',event_type:'REPAIRABLE_DEFECT_RECORDED',category:'REWORK',occurred_at:'2026-08-13T08:35:00Z',actor_name:'Nguyễn Văn A',po_id:1,part_id:2,operation_id:3,session_id:77,title:'Ghi nhận lỗi sửa được',description:'',quantity_delta:2,metadata:{movement_id:8},correlation_id:'corr-finish',session_trace_id:'trace-77',source:'NATIVE'},
 {id:'7',event_type:'DEFECT_QUANTITY_RECORDED',category:'DEFECT',occurred_at:'2026-08-13T08:34:00Z',actor_name:'Nguyễn Văn A',po_id:1,part_id:2,operation_id:3,session_id:77,title:'Ghi nhận sản lượng lỗi',description:'',quantity_delta:3,metadata:{movement_id:7},correlation_id:'corr-finish',session_trace_id:'trace-77',source:'NATIVE'},
 {id:'6',event_type:'GOOD_QUANTITY_RECORDED',category:'QUANTITY',occurred_at:'2026-08-13T08:33:00Z',actor_name:'Nguyễn Văn A',po_id:1,part_id:2,operation_id:3,session_id:77,title:'Ghi nhận sản lượng đạt',description:'',quantity_delta:20,metadata:{movement_id:6},correlation_id:'corr-finish',session_trace_id:'trace-77',source:'NATIVE'},
 {id:'5',event_type:'SESSION_STARTED',category:'SESSION',occurred_at:'2026-08-13T07:30:00Z',actor_name:'Nguyễn Văn A',po_id:1,part_id:2,operation_id:3,session_id:77,title:'Session bắt đầu',description:'OP Chấn',quantity_delta:null,metadata:{employee_id:4},correlation_id:'corr-start',session_trace_id:'trace-77',source:'NATIVE'}];
async function mock(page){await page.route(/\/api\/production-orders\?limit=1000/,r=>r.fulfill({json:{ok:true,items:[{id:1,code:'PO-260813-001',product:'Vỏ tủ điện'}]}}));await page.route(/\/api\/production-orders\/1\/trace.*/,r=>r.fulfill({json:{ok:true,context:{po_id:1,po_code:'PO-260813-001',status:'IN_PROGRESS',planned_quantity:200},events,next_before:null,has_more:false,coverage:{native_from_version:'68.0.0.1'}}}));await page.route('/api/production-orders/1/quantity-history',r=>r.fulfill({json:{ok:true,items:[],reconciliation:{current:{good_qty:118,defect_qty:3,rework_qty:2},ledger:{good_qty:118,defect_qty:3,rework_qty:2},matches:true}}}));}
test('PO Production Trace, quantity/rework và Change Audit',async({page})=>{await page.setViewportSize({width:1920,height:1080});await login(page);await mock(page);await page.evaluate(()=>openPage('production-trace'));await page.locator('#ptPo').selectOption('1');await expect(page.locator('.trace-event')).toHaveCount(5);await expect(page.locator('.trace-summary')).toContainText('118');await page.screenshot({path:'test-results/v68-po-production-trace.png',fullPage:true});await page.locator('.cat-rework details summary').click();await page.screenshot({path:'test-results/v68-expanded-quantity-rework.png',fullPage:true});await expect(page.locator('.trace-diff')).toContainText('120 → 118');await page.screenshot({path:'test-results/v68-change-audit.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});
test('Session Drawer dùng V68 normalized timeline',async({page})=>{await page.setViewportSize({width:1366,height:768});await login(page);await page.route('/api/session-management/77',r=>r.fulfill({json:{ok:true,session:{session_id:77,status:'CLOSED',employee_name:'Nguyễn Văn A',employee_code:'NV-001',po_code:'PO-260813-001',part_code:'P-01',operation_code:'OP-CHAN',operation_name:'Chấn',started_at:'2026-08-13T07:30:00Z',ended_at:'2026-08-13T08:40:00Z',duration_seconds:4200,good_qty:118,defect_qty:3,rework_qty:2},activity:[],exceptions:[],reviews:[]}}));await page.route(/\/api\/sessions\/77\/trace.*/,r=>r.fulfill({json:{ok:true,events,context:{},has_more:false}}));await page.evaluate(()=>SessionDetailDrawer.open(77));await expect(page.locator('.trace-mini')).toContainText('Ghi nhận sản lượng đạt');await page.screenshot({path:'test-results/v68-session-drawer-timeline.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});
