"""MESFlow Report Engine (P0, issue #33).

One validated request (schema.ReportRequest) -> one dataset loader that
reuses the EXISTING, already-authorized report queries (datasets.py; no
new SQL, never SQL generated by AI) -> one neutral ReportDocument ->
renderers: XLSX via XlsxWriter (xlsx.py, openpyxl fallback) and PDF via
WeasyPrint over an HTML/CSS print layout (pdf.py, HTML fallback when the
native libraries are missing).

openpyxl stays the tool for EDITING existing workbooks (router export,
template import/export); this engine only creates new files.

HTTP entry points live in mesflow.web.report_engine. A chatbot / other
caller should go through build_report() so it gets the same validation,
permission check and numbers as the UI.
"""
from mesflow.reporting.schema import ReportRequest, ReportValidationError, parse_report_request
from mesflow.reporting.datasets import DATASETS, ReportDocument, build_document, can_access
from mesflow.reporting.engine import RenderedReport, PdfEngineUnavailable, build_report, capabilities

__all__ = [
    'DATASETS', 'PdfEngineUnavailable', 'RenderedReport', 'ReportDocument', 'ReportRequest',
    'ReportValidationError', 'build_document', 'build_report', 'can_access', 'capabilities',
    'parse_report_request',
]
