#!/usr/bin/env bash
# Deterministic CI/test fixture for the ESP Kiosk tutorial feature
# (tests/e2e/mesflow.spec.js "ESP Kiosk tutorial loads seven runtime
# videos and plays").
#
# The real manifest/videos at runtime/tutorials/esp-kiosk/ are produced
# by a separate device-capture pipeline (see the real manifest's own
# generator_fingerprint/capture_method/source_commit fields) and are
# deliberately gitignored (AGENTS.md rule 8: "Runtime/data/artifacts do
# not belong in the source repository") -- a fresh checkout (any
# developer machine, and every CI run) never has them, so the E2E test
# was failing everywhere except a machine that happened to already have
# a real capture sitting in runtime/.
#
# This script does NOT try to reproduce or depend on that real capture.
# It generates a fully synthetic, self-contained fixture -- 7 tiny, real,
# genuinely browser-playable MP4s (ffmpeg's own deterministic testsrc2
# pattern generator, no external inputs, no network) plus a manifest.json
# whose structure/video count/tutorial_version matches the real contract
# exactly (same 7 filenames/titles/order the real capture pipeline
# produces, so this stays a faithful stand-in, not an arbitrary shape).
#
# Run before bringing up compose.test.yml's mesflow-test-api (which
# bind-mounts ./runtime/tutorials read-only) -- see scripts/test/docker-test.sh.
set -Eeuo pipefail
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
cd "$ROOT"

TUTORIAL_VERSION="5.1.9.2"
OUT_DIR="runtime/tutorials/esp-kiosk"
VIDEOS_DIR="$OUT_DIR/videos"

if ! command -v ffmpeg >/dev/null 2>&1; then
  # Real finding (GitHub Actions PR #7, run 33222513717): ffmpeg is NOT
  # actually present on this project's ubuntu-latest runners -- do not
  # assume it. Install it the same way any other CI setup step would
  # (apt-get, via the runner's own passwordless sudo); fail loudly, not
  # silently, if that isn't possible either (e.g. a locked-down host
  # with neither ffmpeg nor package-install rights).
  echo "GENERATE_ESP_TUTORIAL_FIXTURE: ffmpeg not found on PATH -- installing it." >&2
  if command -v apt-get >/dev/null 2>&1; then
    SUDO=""
    if [ "$(id -u)" -ne 0 ]; then
      if command -v sudo >/dev/null 2>&1; then SUDO="sudo"; else
        echo "GENERATE_ESP_TUTORIAL_FIXTURE: not root and no sudo available -- cannot install ffmpeg." >&2
        exit 1
      fi
    fi
    $SUDO apt-get update -qq && $SUDO apt-get install -y -qq --no-install-recommends ffmpeg
  fi
  if ! command -v ffmpeg >/dev/null 2>&1; then
    echo "GENERATE_ESP_TUTORIAL_FIXTURE: ffmpeg still not on PATH after attempting installation -- required to synthesize real, playable test videos." >&2
    exit 1
  fi
fi

# Never clobber a developer's real, device-captured manifest -- only
# overwrite a manifest this same script generated before (or none at
# all). A real capture already satisfying the same contract (7 videos,
# version 5.1.9.2) needs no replacing either way; a real capture that
# DOESN'T match should fail the test loudly so the mismatch is visible,
# not be silently papered over by this script.
if [ -f "$OUT_DIR/manifest.json" ] && ! grep -q '"generated_by": *"scripts/test/generate-esp-tutorial-fixture.sh"' "$OUT_DIR/manifest.json"; then
  echo "GENERATE_ESP_TUTORIAL_FIXTURE: $OUT_DIR/manifest.json already exists and was not generated by this script -- leaving a real/manually-provided fixture in place, untouched."
  exit 0
fi

mkdir -p "$VIDEOS_DIR"

# id / filename / title (Vietnamese, matches the real production manifest
# verbatim) / order / duration_seconds -- one line per required video.
entries=(
  "00_kiosk_overview|Tổng quan ESP Kiosk|0|2"
  "01_kiosk_boot_connect|Khởi động và kết nối|1|2"
  "02_kiosk_start_session|Bắt đầu phiên làm việc|2|2"
  "03_kiosk_finish_good_qty|Kết thúc: chỉ có sản phẩm đạt|3|2"
  "04_kiosk_defect_rework|Kết thúc: có lỗi|4|2"
  "05_kiosk_common_errors|Các lỗi thường gặp|5|2"
  "06_kiosk_offline_reconnect|Mất mạng và kết nối lại|6|2"
)

videos_json="["
first=1
for entry in "${entries[@]}"; do
  IFS='|' read -r id title order duration <<<"$entry"
  filename="${id}.mp4"
  out="$VIDEOS_DIR/$filename"
  # Deterministic: same seed pattern + fixed duration/size/rate every run,
  # no timestamps or randomness baked into the encoded bytes themselves
  # (encoder metadata like `encoder=` tags may still vary by ffmpeg
  # version, which is fine -- determinism here means "always regenerates
  # a valid, playable video with these exact filenames/order", not
  # byte-identical output across ffmpeg versions).
  ffmpeg -y -hide_banner -loglevel error \
    -f lavfi -i "testsrc2=size=320x240:rate=10:duration=${duration}" \
    -c:v libx264 -preset ultrafast -pix_fmt yuv420p -movflags +faststart \
    "$out"
  if [ "$first" -eq 1 ]; then first=0; else videos_json+=","; fi
  videos_json+=$(python3 - "$id" "$filename" "$title" "$order" "$duration" <<'PY'
import json, sys
_id, filename, title, order, duration = sys.argv[1:6]
print(json.dumps({"id": _id, "filename": filename, "title": title, "order": int(order), "duration_seconds": int(duration)}))
PY
)
done
videos_json+="]"

python3 - "$OUT_DIR/manifest.json" "$TUTORIAL_VERSION" "$videos_json" <<'PY'
import json, sys
path, version, videos_json = sys.argv[1:4]
manifest = {
    "type": "esp-kiosk-tutorial",
    "tutorial_version": version,
    "generated_by": "scripts/test/generate-esp-tutorial-fixture.sh",
    "videos": json.loads(videos_json),
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, ensure_ascii=False, indent=2)
    f.write("\n")
PY

echo "GENERATE_ESP_TUTORIAL_FIXTURE: wrote $OUT_DIR/manifest.json + ${#entries[@]} videos"
